const list = [
  {
    en: "Americas",
    cn: "美洲",
    hk: "美洲",
    ja: "アメリカ",
    de: "Nord- und Südamerika",
    fr: "Amériques",
    ko: "북미",
    es: "América",
    it: "Nord America",
    countries: [
      {
        country_code: "us",
        continent_code: "north america",
        country: "United States",
        country_cn: "美国",
        country_english: "United States",
        currency: "USD",
        currency_symbol: "$",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "ca_en",
        continent_code: "north america",
        country: "Canada",
        country_cn: "加拿大",
        country_english: "Canada",
        currency: "USD",
        currency_symbol: "$",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "ca",
        continent_code: "north america",
        country: "Canada",
        country_cn: "加拿大",
        country_english: "Canada",
        currency: "USD",
        currency_symbol: "$",
        language_code: "fr",
        language: "Français",
      },
      {
        country_code: "pr",
        continent_code: "north america",
        country: "Puerto Rico",
        country_cn: "波多黎各",
        country_english: "Puerto Rico",
        currency: "USD",
        currency_symbol: "$",
        language_code: "en",
        language: "English",
      },
    ],
  },
  {
    en: "Middle East",
    cn: "中东",
    hk: "中東",
    ja: "中東",
    de: "Mittlerer Osten",
    fr: "Moyen-Orient",
    ko: "중동",
    es: "Medio Oriente",
    it: "Medio Oriente",
    countries: [
      {
        country_code: "kw",
        continent_code: "asia pacific",
        country: "Kuwait",
        country_cn: "科威特",
        country_english: "Kuwait",
        currency: "USD",
        currency_symbol: "$",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "sa",
        continent_code: "asia pacific",
        country: "Saudi Arabia",
        country_cn: "沙特阿拉伯",
        country_english: "Saudi Arabia",
        currency: "USD",
        currency_symbol: "$",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "ae",
        continent_code: "asia pacific",
        country: "UAE",
        country_cn: "阿拉伯联合酋长国",
        country_english: "United Arab Emirates",
        currency: "USD",
        currency_symbol: "$",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "il",
        continent_code: "asia pacific",
        country: "Israel",
        country_cn: "以色列",
        country_english: "Israel",
        currency: "USD",
        currency_symbol: "$",
        language_code: "en",
        language: "English",
      },
    ],
  },
  {
    en: "Asia Pacific",
    cn: "亚太",
    hk: "亞太",
    ja: "アジア太平洋",
    de: "Asien-Pazifik",
    fr: "Asie Pacifique",
    ko: "아시아 태평양",
    es: "Asia Pacífico",
    it: "Asia Pacifica",
    countries: [
      {
        country_code: "c2",
        continent_code: "asia pacific",
        country: "中国大陆",
        country_cn: "中国大陆",
        country_english: "China",
        currency: "CNY",
        currency_symbol: "¥",
        currency_subunit_to_unit: 100,
        language_code: "cn",
        language: "简体中文",
      },
      {
        country_code: "hk",
        continent_code: "asia pacific",
        country: "香港",
        country_cn: "香港",
        country_english: "Hong Kong",
        currency: "HKD",
        currency_symbol: "$",
        currency_subunit_to_unit: 100,
        language_code: "hk",
        language: "繁体中文",
      },
      {
        country_code: "hk_en",
        continent_code: "asia pacific",
        country: "Hong Kong",
        country_cn: "香港",
        country_english: "Hong Kong",
        currency: "HKD",
        currency_symbol: "$",
        currency_subunit_to_unit: 100,
        language_code: "en",
        language: "English",
      },
      {
        country_code: "jp",
        continent_code: "asia pacific",
        country: "日本",
        country_cn: "日本",
        country_english: "Japan",
        currency: "JPY",
        currency_symbol: "¥",
        currency_subunit_to_unit: 1,
        language_code: "ja",
        language: "日本語",
      },
      {
        country_code: "mo",
        continent_code: "asia pacific",
        country: "澳门",
        country_cn: "澳门",
        country_english: "Macau",
        currency: "USD",
        currency_symbol: "$",
        currency_subunit_to_unit: 100,
        language_code: "hk",
        language: "繁体中文",
      },
      {
        country_code: "sg",
        continent_code: "asia pacific",
        country: "Singapore",
        country_cn: "新加坡",
        country_english: "Singapore",
        currency: "USD",
        currency_symbol: "$",
        currency_subunit_to_unit: 100,
        language_code: "en",
        language: "English",
      },
      {
        country_code: "kr",
        continent_code: "asia pacific",
        country: "대한민국",
        country_cn: "韩国",
        country_english: "South Korea",
        currency: "USD",
        currency_symbol: "$",
        currency_subunit_to_unit: 1,
        language_code: "ko",
        language: "한국어",
      },
      {
        country_code: "tw",
        continent_code: "asia pacific",
        country: "台湾",
        country_cn: "中国台湾",
        country_english: "Taiwan",
        currency: "TWD",
        currency_symbol: "$",
        currency_subunit_to_unit: 100,
        language_code: "hk",
        language: "繁体中文",
      },
      {
        country_code: "au",
        continent_code: "asia pacific",
        country: "Australia",
        country_cn: "澳大利亚",
        country_english: "Australia",
        currency: "AUD",
        currency_symbol: "$",
        currency_subunit_to_unit: 100,
        language_code: "en",
        language: "English",
      },
      {
        country_code: "nz",
        continent_code: "asia pacific",
        country: "New Zealand",
        country_cn: "新西兰",
        country_english: "New Zealand",
        currency: "AUD",
        currency_symbol: "$",
        currency_subunit_to_unit: 100,
        language_code: "en",
        language: "English",
      },
    ],
  },
  {
    en: "Europe",
    cn: "欧洲",
    hk: "歐洲",
    ja: "欧州",
    de: "Europa",
    fr: "Europe",
    ko: "유럽",
    es: "Europa",
    it: "Europa",
    countries: [
      {
        country_code: "at",
        continent_code: "europe",
        country: "Österreich",
        country_cn: "奥地利",
        country_english: "Austria",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "de",
        language: "Deutsch",
      },
      {
        country_code: "be",
        continent_code: "europe",
        country: "Belgium",
        country_cn: "比利时",
        country_english: "Belgium",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "bg",
        continent_code: "europe",
        country: "Bulgaria",
        country_cn: "保加利亚",
        country_english: "Bulgaria",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "hr",
        continent_code: "europe",
        country: "Croatia",
        country_cn: "克罗地亚",
        country_english: "Croatia",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "cz",
        continent_code: "europe",
        country: "Czech Republic",
        country_cn: "捷克",
        country_english: "Czech Republic",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "dk",
        continent_code: "europe",
        country: "Denmark",
        country_cn: "丹麦",
        country_english: "Denmark",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "ee",
        continent_code: "europe",
        country: "Estonia",
        country_cn: "爱沙尼亚",
        country_english: "Estonia",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "fi",
        continent_code: "europe",
        country: "Finland",
        country_cn: "芬兰",
        country_english: "Finland",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "fr",
        continent_code: "europe",
        country: "France",
        country_cn: "法国",
        country_english: "France",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "fr",
        language: "Français",
      },
      {
        country_code: "de",
        continent_code: "europe",
        country: "Deutschland",
        country_cn: "德国",
        country_english: "Germany",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "de",
        language: "Deutsch",
      },
      {
        country_code: "gr",
        continent_code: "europe",
        country: "Greece",
        country_cn: "希腊",
        country_english: "Greece",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "hu",
        continent_code: "europe",
        country: "Hungary",
        country_cn: "匈牙利",
        country_english: "Hungary",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "ie",
        continent_code: "europe",
        country: "Ireland",
        country_cn: "爱尔兰",
        country_english: "Ireland",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "it",
        continent_code: "europe",
        country: "Italia",
        country_cn: "意大利",
        country_english: "Italy",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "it",
        language: "Italiano",
      },
      {
        country_code: "lv",
        continent_code: "europe",
        country: "Latvia",
        country_cn: "拉脱维亚",
        country_english: "Latvia",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "li",
        continent_code: "europe",
        country: "Liechtenstein",
        country_cn: "列支敦士登",
        country_english: "Liechtenstein",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "de",
        language: "Deutsch",
      },
      {
        country_code: "lt",
        continent_code: "europe",
        country: "Lithuania",
        country_cn: "立陶宛",
        country_english: "Lithuania",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "lu",
        continent_code: "europe",
        country: "Luxembourg",
        country_cn: "卢森堡",
        country_english: "Luxembourg",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "fr",
        language: "Français",
      },
      {
        country_code: "mt",
        continent_code: "europe",
        country: "Malta",
        country_cn: "马耳他",
        country_english: "Malta",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "mc",
        continent_code: "europe",
        country: "Monaco",
        country_cn: "摩纳哥",
        country_english: "Monaco",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "fr",
        language: "Français",
      },
      {
        country_code: "nl",
        continent_code: "europe",
        country: "Netherlands",
        country_cn: "荷兰",
        country_english: "Netherlands",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "no",
        continent_code: "europe",
        country: "Norway",
        country_cn: "挪威",
        country_english: "Norway",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "pl",
        continent_code: "europe",
        country: "Poland",
        country_cn: "波兰",
        country_english: "Poland",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "pt",
        continent_code: "europe",
        country: "Portugal",
        country_cn: "葡萄牙",
        country_english: "Portugal",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "sk",
        continent_code: "europe",
        country: "Slovakia",
        country_cn: "斯洛伐克",
        country_english: "Slovakia",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "si",
        continent_code: "europe",
        country: "Slovenia",
        country_cn: "斯洛文尼亚",
        country_english: "Slovenia",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "es",
        continent_code: "europe",
        country: "España",
        country_cn: "西班牙",
        country_english: "Spain",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "es",
        language: "Español",
      },
      {
        country_code: "se",
        continent_code: "europe",
        country: "Sweden",
        country_cn: "瑞典",
        country_english: "Sweden",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "ch",
        continent_code: "europe",
        country: "Switzerland",
        country_cn: "瑞士",
        country_english: "Switzerland",
        currency: "EUR",
        currency_symbol: "€",
        language_code: "en",
        language: "English",
      },
      {
        country_code: "gb",
        continent_code: "europe",
        country: "United Kingdom",
        country_cn: "英国",
        country_english: "United Kingdom",
        currency: "GBP",
        currency_symbol: "£",
        language_code: "en",
        language: "English",
      },
    ],
  },
];

/**
 * @param {list} 列表
 * @param {map} 键值对
 */
module.exports = (key = "list") => {
  if (key === "list") {
    return list;
  } else if (key === "map") {
    let obj = {};
    list.forEach((item) => {
      item.countries.forEach((country) => {
        obj[country.country_code] = country;
      });
    });
    return obj;
  }
};
